### Variables
@host = http://localhost:7071
@user_id = user591

### api/list-images-test
# @name api/list-images-test
POST {{host}}/api/init-user-test
Accept: application/json

{
  "prompt": "init my foder on blob.",
  "user_id": "{{user_id}}"
}
