### Variables
@host = http://localhost:7071

### websearch-test
# @name websearch-test
POST {{host}}/api/websearch-test
Accept: application/json

{
  "prompt": "Quel temps fait il à Paris aujourd'hui ?"
}
